### ISSUE TITLE
Spoilers log current settings, not those used during randomization

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer#40]
### Problem
The spoiler logs generate files that log the current settings for the randomizer. This is intended to be a way to know what was and wasn't randomized to assist debugging/troubleshooting for developers and understanding what was randomized for the user. However, the user can modify the settings while the game is still randomized and then generate spoilers with incorrect settings.

### Potential Solution
The randomizer generates a KRP file when the game is randomized that contains all of the active settings at the time. If this file is parsed, then the randomization settings should be accurate. Some settings might not be stored in the KRP file, but I think that only consists of a few items.

**Comment by LaneDibello** [comment]
We could also consider migrating the spoiler log feature to immediately after randomizing. Picture: "Randomizing Compete! Would you like to generate a spoiler log? Yes/No" This way spoilers are only generated when desired, and there's no rush of changing settings before making the log. The drawback being no generating spoilers after the fact.
