### ISSUE TITLE
Unable to talk to certain NPCs because Conversation Error

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer#46]
### Summary
When starting a conversation with certain NPCs or Terminals, an error message pops up - see the image below. Spoiler logs of an example will be provided later, but in this example the Terminal at the end of the Endar Spire and Roland Wann on Manaan.

![image](https://user-images.githubusercontent.com/8595914/110388402-09bbfd80-8031-11eb-8653-183e5eae6308.png)

**Comment by LaneDibello** [comment]
The glitch is replicated when using exact Text and Module settings. So it is some interaction between the two.

**Comment by LaneDibello** [comment]
After omitting all modules and disabling reachability verification (It throws an exception if you don't btw), the glitch is solved.

**Comment by LaneDibello** [comment]
I believe the issue is there is currently no Text validation for the Reply rando so its possible to get an empty string as a reply, which the dialogue tree interprets as a [CONTINUE] node, breaking the conversation. I'll put a patch together and see if this solves the problem.

**Comment by TheBrino1** [comment]
![Screenshot (3)](https://github.com/LaneDibello/Kotor-Randomizer/assets/173305927/fad5aff2-2115-44fc-8611-e17d225b7271)

I can't progress the story because I can't use this elevator. The Message, "CONVERSATION ERROR: Last Conversation Node Contains Either an NODE or CONTINUE NODE..." I don't use mods. any help would be great.

**Comment by TheBrino1** [comment]
A computer menu pops up for half a millisecond before closing and displaying the text in the photo.
