### ISSUE TITLE
Invisible character models crashed the game

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer#51]
When walking across the bridge in Upper City North (tar_m02ab), the drunks were invisible and when their conversation was triggered, the game crashed.

Awaiting seed and spoiler logs...

**Comment by glasnonck** [comment]
### Relevant Settings
- Seed: 40662
- Item: All "Type" except...
  - Creature Hides: None
  - Creature Weapons: None
  - Upgrades/Crystals: Subtype
  - Various: None

### Issue Investigation
Lane found that the crash still occurred when using only Item randomization. The drunks are wearing "Clothing Variant 4" (g_a_clothes04) which were shuffled to be "Darth Revan's Robes" (g_a_mstrrobe06).  Using Kotor_Tool, I verified that this change is sufficient to reproduce the crash with only one of the drunks (tar02_drunk021.utc). The game doesn't crash immediately if only one of the other drunks has the item equipped - the crash occurs once that drunk has dialog to speak. This isn't something that would happen normally since all the drunks have the same clothing equipped, but it could be useful for determining exactly why this crash occurs.

### Potential Solutions
We would prefer to keep this item in the shuffle since it doesn't break your party members, but the simplest solution would be to skip this item during the shuffle.

Other solutions may be possible if we better understood the cause of this crash.

**Comment by glasnonck** [comment]
I added clothing variant 4 to the Omit Items list. This is the simplest fix for the issue, and as the clothing variants are only used by NPCs, this shouldn't affect the player too much. In the future, we may add a different method of handling item shuffles that break the game.

**Comment by LaneDibello** [comment]
A similar but not identical glitch Occurred for Indy in a recent run. In this case Uthar was character model randomized Model randomized to Darth Bandon (who as we discovered from party rando does not like having items equipped to his chest slot). Because Uthar was wearing clothing05 in his chest slot, the game could not render Bandon and crashed.
