### ISSUE TITLE
Taris-based plot items are removed from your inventory

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer#73]
The Taris-based plot items are removed whenever you arrive at the Jedi Enclave. There should be an option to stop this from happening, as we never know how many times a player might travel through Taris and the Enclave when the game is randomized.

**Comment by LaneDibello** [comment]
So the solution is actually quite elegant, I just changed the item references for the Taris Plot items in k_pdan_13_area.ncs to strings of v's of the same length, using a hex editor. This solved the problem! A patch should be coming soon.
