### ISSUE TITLE
Migrate to .NET 7

### ISSUE THREAD

**Issue by glasnonck** [LaneDibello/Kotor-Randomizer#98]
The .NET framework version we are using is no longer supported. If we continue with .NET framework, at least upgrade to the supported version 4.8.

The better option moving forward is to migrate to .NET 6. Swapping would allow use of newer C# versions as well as speed/optimization improvements. A console tool called upgrade-assistant can assist by automating some of that transition.

**Comment by LaneDibello** [comment]
We waited so long, .Net 7 made more sense.

I was originally considering hopping to 8, but that seemed to break things with some dependencies. So we'll start with 7, get our ducks in a row, and look towards 8 in the future.
